name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "**.xml"
      - "**.ipynb"
      - "Examples/**"
      - "Docs/**"
      - ".vscode/**"
  workflow_dispatch:
    branches:
      - main
    inputs:
      tag:
        required: false
        default: all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

jobs:
  Tests_WinPS5:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v3

      - name: Install Pester
        run: Install-Module Pester -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Test
        run: |
          $pesterParam = @{CI = $true; Output = 'Detailed'}
          if('${{ inputs.tag }}' -eq ''){$pesterParam.Tag = 'Offline'}
          elseif('${{ inputs.tag }}' -ne 'all'){$pesterParam.Tag = '${{ inputs.tag }}'}
          Invoke-Pester @pesterParam

  Tests_PS7:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: pwsh

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v3

      - name: Install Pester
        run: Install-Module Pester -Force -AllowClobber -Scope CurrentUser -SkipPublisherCheck

      - name: Test
        run: |
          $pesterParam = @{CI = $true; Output = 'Detailed'}
          if('${{ inputs.tag }}' -eq ''){$pesterParam.Tag = 'Offline'}
          elseif('${{ inputs.tag }}' -ne 'all'){$pesterParam.Tag = '${{ inputs.tag }}'}
          Invoke-Pester @pesterParam
